import type { Metadata} from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";

import { Separator } from "@/components/ui/separator";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Contact Card Lists",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <header className="p-6">
               <Link href="/">
                  <h1 className="text-2xl font-bold my-4">MEJI Degital</h1>
                  <Separator />
               </Link>
            </header>
            <main className="p-6">{children}</main>
            <Toaster/>
         </body>
      </html>
   );
}
